import { v4 as uuid } from "uuid";

import sun3 from "../../assets/sunglasses/sun3.png";
import sun4 from "../../assets/sunglasses/sun4.png";
import sun5 from "../../assets/sunglasses/sun5.png";
import sun7 from "../../assets/sunglasses/sun7.png";
import sun8 from "../../assets/sunglasses/sun8.png";
import sun9 from "../../assets/sunglasses/sun9.png";
import sun10 from "../../assets/sunglasses/sun10.png";
import sun11 from "../../assets/sunglasses/sun11.png";
import sun12 from "../../assets/sunglasses/sun12.png";
import sun13 from "../../assets/sunglasses/sun13.png";
import sun14 from "../../assets/sunglasses/sun14.png";

import sports1 from "../../assets/sports/sports1.png";
import sports2 from "../../assets/sports/sports2.png";
import sports3 from "../../assets/sports/sports3.png";
import sports4 from "../../assets/sports/sports4.png";
import sports6 from "../../assets/sports/sports6.png";
import sports7 from "../../assets/sports/sports7.png";
import sports8 from "../../assets/sports/sports8.png";
import sports9 from "../../assets/sports/sports9.png";

import vision1 from "../../assets/vision/vision1.png";
import vision2 from "../../assets/vision/vision2.png";
import vision3 from "../../assets/vision/vision3.png";
import vision4 from "../../assets/vision/vision4.png";
import vision5 from "../../assets/vision/vision5.png";
import vision6 from "../../assets/vision/vision6.png";
import vision7 from "../../assets/vision/vision7.png";
import vision8 from "../../assets/vision/vision8.png";
import vision9 from "../../assets/vision/vision9.png";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
export const products = [
  {
    _id: uuid(),
    qty: 0,
    name: "Ardor Avaitor",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
    category: "Sports",
    gender: "Men",
    weight: "500g",
    quantity: 10,
    image: sports1,
    rating: 4.5,
    price: 1999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Caper Active",
    description: "Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Brand 2",
    category: "Sports",
    gender: "Men",
    weight: "1kg",
    quantity: 5,
    image: sports2,
    rating: 4.2,
    price: 1299.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Alder Street",
    description: "Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Brand 3",
    category: "Sports",
    gender: "Unisex",
    weight: "750g",
    quantity: 15,
    image: sports3,
    rating: 4.7,
    price: 2999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Corral Round",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Brand 4",
    category: "Sports",
    gender: "Unisex",
    weight: "300g",
    quantity: 8,
    image: sports4,
    rating: 3.8,
    price: 2499.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Hyperclax Active",
    description: "Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Brand 5",
    category: "Sports",
    gender: "Women",
    weight: "900g",
    quantity: 3,
    image: sports6,
    rating: 4.6,
    price: 3999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Rose Gold Chase",
    description: "Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Brand 1",
    category: "Vision",
    gender: "Women",
    weight: "1.2kg",
    quantity: 9,
    image: vision7,
    rating: 4.3,
    price: 2999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Full Rim Airflex",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Vision",
    gender: "Unisex",
    weight: "550g",
    quantity: 7,
    image: vision8,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Mercury Rounded Red",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Vision",
    gender: "Unisex",
    weight: "550g",
    quantity: 7,
    image: vision9,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Candyfloss-302",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
    category: "Sunglasses",
    gender: "Men",
    weight: "500g",
    quantity: 10,
    image: sun3,
    rating: 4.5,
    price: 1999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Phenomenal Mercury-02",
    description: "Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Brand 2",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "1kg",
    quantity: 5,
    image: sun4,
    rating: 4.2,
    price: 1299.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Black rounded boss",
    description: "Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Brand 3",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "750g",
    quantity: 15,
    image: sun5,
    rating: 4.7,
    price: 2999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Blue Ray Wayfarer",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Sports",
    gender: "Unisex",
    weight: "550g",
    quantity: 7,
    image: sports9,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Pernik",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Brand 4",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "300g",
    quantity: 8,
    image: sun7,
    rating: 3.8,
    price: 2499.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Silistra",
    description: "Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Brand 5",
    category: "Sunglasses",
    gender: "Women",
    weight: "900g",
    quantity: 3,
    image: sun8,
    rating: 4.6,
    price: 3999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Full rim acetate black",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
    category: "Vision",
    gender: "Men",
    weight: "500g",
    quantity: 10,
    image: vision1,
    rating: 4.5,
    price: 1999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Ruse",
    description: "Fusce sed est nec ipsum convallis semper nec id ipsum.",
    brand: "Brand 3",
    category: "Sunglasses",
    gender: "Men",
    weight: "400g",
    quantity: 6,
    image: sun9,
    rating: 4.1,
    price: 1499.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Yambol",
    description: "Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Brand 1",
    category: "Sunglasses",
    gender: "Men",
    weight: "1.2kg",
    quantity: 9,
    image: sun10,
    rating: 4.3,
    price: 2999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Roadies Rd-202",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Sunglasses",
    gender: "Men",
    weight: "550g",
    quantity: 7,
    image: sun14,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Burgas",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Sunglasses",
    gender: "Women",
    weight: "550g",
    quantity: 7,
    image: sun11,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Hip Hop Candy",
    description: "Fusce sed est nec ipsum convallis semper nec id ipsum.",
    brand: "Brand 3",
    category: "Sports",
    gender: "Men",
    weight: "400g",
    quantity: 6,
    image: sports7,
    rating: 4.1,
    price: 1499.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Punk Cut Out",
    description: "Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Brand 1",
    category: "Sports",
    gender: "Women",
    weight: "1.2kg",
    quantity: 9,
    image: sports8,
    rating: 4.3,
    price: 2999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Rounded Gold",
    description: "Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Brand 2",
    category: "Vision",
    gender: "Men",
    weight: "1kg",
    quantity: 5,
    image: vision2,
    rating: 4.2,
    price: 1299.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Jungle Safari",
    description: "Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Brand 3",
    category: "Vision",
    gender: "Unisex",
    weight: "750g",
    quantity: 15,
    image: vision3,
    rating: 4.7,
    price: 2999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Burgas",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Sunglasses",
    gender: "Women",
    weight: "550g",
    quantity: 7,
    image: sun11,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Sofia",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Sunglasses",
    gender: "Women",
    weight: "550g",
    quantity: 7,
    image: sun12,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Plovediv",
    description: "Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Brand 4",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "550g",
    quantity: 7,
    image: sun13,
    rating: 4.8,
    price: 4999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Airway Black",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Brand 4",
    category: "Vision",
    gender: "Unisex",
    weight: "300g",
    quantity: 8,
    image: vision4,
    rating: 3.8,
    price: 2499.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Cat-eyed Gold",
    description: "Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Brand 5",
    category: "Vision",
    gender: "Women",
    weight: "900g",
    quantity: 3,
    image: vision5,
    rating: 4.6,
    price: 3999.99,
  },
  {
    _id: uuid(),
    qty: 0,
    name: "Full Rim Steel Gray",
    description: "Fusce sed est nec ipsum convallis semper nec id ipsum.",
    brand: "Brand 3",
    category: "Vision",
    gender: "Men",
    weight: "400g",
    quantity: 6,
    image: vision6,
    rating: 4.1,
    price: 1499.99,
  },
];
const arr = [
  { newPrice: 1899.99 },
  { newPrice: 1199.99 },
  { newPrice: 2899.99 },
  { newPrice: 2399.99 },
  { newPrice: 3899.99 },
  { newPrice: 2899.99 },
  { newPrice: 4899.99 },
  { newPrice: 4899.99 },
  { newPrice: 1899.99 },
  { newPrice: 1199.99 },
  { newPrice: 2899.99 },
  { newPrice: 4899.99 },
  { newPrice: 2399.99 },
  { newPrice: 3899.99 },
  { newPrice: 1899.99 },
  { newPrice: 1399.99 },
  { newPrice: 2899.99 },
  { newPrice: 4899.99 },
  { newPrice: 4899.99 },
  { newPrice: 1399.99 },
  { newPrice: 2899.99 },
  { newPrice: 1199.99 },
  { newPrice: 2899.99 },
  { newPrice: 4899.99 },
  { newPrice: 4899.99 },
  { newPrice: 4899.99 },
  { newPrice: 2399.99 },
  { newPrice: 3899.99 },
  { newPrice: 1399.99 },
];
