export const actionTypes = {
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  INITIALIZE_CART: "INITIALIZE_CART",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",

  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
};
