export const actionTypes = {
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  INITIALIZE_CART: "INITIALIZE_CART",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  UPDATE_PRODUCT_QTY_IN_CART: "UPDATE_PRODUCT_QTY_IN_CART",
  DELETE_PRODUCTS_FROM_CART: "DELETE_PRODUCTS_FROM_CART",
};
